In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("claims_dataset.csv", delimiter="|")
df

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar
0,561205,ferd,1,1,4,3,2
1,528569,ferd,4,3,1,2,4
2,408550,NaN,2,4,1,4,2
3,208451,NaN,1,1,4,1,4
4,394115,ferd,2,4,1,3,4
5,243530,fait,2,1,3,1,2
6,288203,NaN,3,3,4,2,2
7,991981,ferd,3,3,2,1,2
8,435094,chepy,2,1,1,4,3
9,417848,fait,4,3,1,4,4

In [2]:
diccionario_imputacion = {
    'log_total_piezas': 1.4545,
    'marca_vehiculo_encoded': 0,
    'valor_vehiculo': 3560,
    'valor_por_pieza': 150,
    'antiguedad_vehiculo': 1,
    'tipo_poliza': 1,
    'taller': 1,
    'partes_a_reparar': 3,
    'partes_a_reemplazar': 1
}
#df.fillna(diccionario_imputacion)
df

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar
0,561205,ferd,1,1,4,3,2
1,528569,ferd,4,3,1,2,4
2,408550,NaN,2,4,1,4,2
3,208451,NaN,1,1,4,1,4
4,394115,ferd,2,4,1,3,4
5,243530,fait,2,1,3,1,2
6,288203,NaN,3,3,4,2,2
7,991981,ferd,3,3,2,1,2
8,435094,chepy,2,1,1,4,3
9,417848,fait,4,3,1,4,4

In [3]:
import dill

with open('app/pipeline_1.pkl', 'rb') as file:
    # Load the object
    pipeline_1 = dill.load(file)
with open('app/pipeline_2.pkl', 'rb') as file:
    # Load the object
    pipeline_2 = dill.load(file)
with open('app/pipeline_3.pkl', 'rb') as file:
    # Load the object
    pipeline_3 = dill.load(file)
with open('app/pipeline_4.pkl', 'rb') as file:
    # Load the object
    pipeline_4 = dill.load(file)
with open('app/pipeline_5.pkl', 'rb') as file:
    # Load the object
    pipeline_5 = dill.load(file)
with open('app/linnear_regression.pkl', 'rb') as file:
    # Load the object
    linnear_regression = dill.load(file)

/home/enju/desafio-hdi/.venv/lib/python3.11/site-packages/sklearn/base.py:463: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.3.0 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
# me da el total de piezas
pipeline_1(df)

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar,total_piezas
0,561205,ferd,1,1,4,3,2,5
1,528569,ferd,4,3,1,2,4,6
2,408550,NaN,2,4,1,4,2,6
3,208451,NaN,1,1,4,1,4,5
4,394115,ferd,2,4,1,3,4,7
5,243530,fait,2,1,3,1,2,3
6,288203,NaN,3,3,4,2,2,4
7,991981,ferd,3,3,2,1,2,3
8,435094,chepy,2,1,1,4,3,7
9,417848,fait,4,3,1,4,4,8

In [5]:
#log del total de piezas
pipeline_2(df)

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar,total_piezas,log_total_piezas
0,561205,ferd,1,1,4,3,2,5,1.609438
1,528569,ferd,4,3,1,2,4,6,1.791759
2,408550,NaN,2,4,1,4,2,6,1.791759
3,208451,NaN,1,1,4,1,4,5,1.609438
4,394115,ferd,2,4,1,3,4,7,1.945910
5,243530,fait,2,1,3,1,2,3,1.098612
6,288203,NaN,3,3,4,2,2,4,1.386294
7,991981,ferd,3,3,2,1,2,3,1.098612
8,435094,chepy,2,1,1,4,3,7,1.945910
9,417848,fait,4,3,1,4,4,8,2.079442

In [6]:
# marca del vehiculo encoded
pipeline_3(df)

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar,total_piezas,log_total_piezas,marca_vehiculo_encoded
0,561205,ferd,1,1,4,3,2,5,1.609438,3.0
1,528569,ferd,4,3,1,2,4,6,1.791759,3.0
2,408550,NaN,2,4,1,4,2,6,1.791759,NaN
3,208451,NaN,1,1,4,1,4,5,1.609438,NaN
4,394115,ferd,2,4,1,3,4,7,1.945910,3.0
5,243530,fait,2,1,3,1,2,3,1.098612,2.0
6,288203,NaN,3,3,4,2,2,4,1.386294,NaN
7,991981,ferd,3,3,2,1,2,3,1.098612,3.0
8,435094,chepy,2,1,1,4,3,7,1.945910,1.0
9,417848,fait,4,3,1,4,4,8,2.079442,2.0

In [7]:
df

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar,total_piezas,log_total_piezas,marca_vehiculo_encoded
0,561205,ferd,1,1,4,3,2,5,1.609438,3.0
1,528569,ferd,4,3,1,2,4,6,1.791759,3.0
2,408550,NaN,2,4,1,4,2,6,1.791759,NaN
3,208451,NaN,1,1,4,1,4,5,1.609438,NaN
4,394115,ferd,2,4,1,3,4,7,1.945910,3.0
5,243530,fait,2,1,3,1,2,3,1.098612,2.0
6,288203,NaN,3,3,4,2,2,4,1.386294,NaN
7,991981,ferd,3,3,2,1,2,3,1.098612,3.0
8,435094,chepy,2,1,1,4,3,7,1.945910,1.0
9,417848,fait,4,3,1,4,4,8,2.079442,2.0

In [8]:
# me da el valor del vehiculo y el valor por pieza
pipeline_4(df)

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar,total_piezas,log_total_piezas,marca_vehiculo_encoded,valor_vehiculo,valor_por_pieza
0,561205,ferd,1,1,4,3,2,5,1.609438,3.0,8540.0,300
1,528569,ferd,4,3,1,2,4,6,1.791759,3.0,8540.0,50
2,408550,NaN,2,4,1,4,2,6,1.791759,NaN,NaN,50
3,208451,NaN,1,1,4,1,4,5,1.609438,NaN,NaN,300
4,394115,ferd,2,4,1,3,4,7,1.945910,3.0,8540.0,50
5,243530,fait,2,1,3,1,2,3,1.098612,2.0,2950.0,200
6,288203,NaN,3,3,4,2,2,4,1.386294,NaN,NaN,300
7,991981,ferd,3,3,2,1,2,3,1.098612,3.0,8540.0,100
8,435094,chepy,2,1,1,4,3,7,1.945910,1.0,1500.0,50
9,417848,fait,4,3,1,4,4,8,2.079442,2.0,2950.0,50

In [9]:
# reclamos por marca y por taller
#pipeline_5(df)

In [10]:
df = df.fillna(diccionario_imputacion)

In [14]:
df[["log_total_piezas","marca_vehiculo_encoded","valor_vehiculo","valor_por_pieza","antiguedad_vehiculo"]]

,log_total_piezas,marca_vehiculo_encoded,valor_vehiculo,valor_por_pieza,antiguedad_vehiculo
0,1.609438,3.0,8540.0,300,1
1,1.791759,3.0,8540.0,50,4
2,1.791759,0.0,3560.0,50,2
3,1.609438,0.0,3560.0,300,1
4,1.945910,3.0,8540.0,50,2
5,1.098612,2.0,2950.0,200,2
6,1.386294,0.0,3560.0,300,3
7,1.098612,3.0,8540.0,100,3
8,1.945910,1.0,1500.0,50,2
9,2.079442,2.0,2950.0,50,4

In [12]:
# - 'log_total_piezas': float64
# - 'marca_vehiculo_encoded': int64
# - 'valor_vehiculo': int64
# - 'valor_por_pieza': int64
# - 'antiguedad_vehiculo': int64

#X = {"log_total_piezas" : [1.4545],"marca_vehiculo_encoded": [1],"valor_vehiculo": [3560], "valor_por_pieza": [150],"antiguedad_vehiculo": [1]}
#X = {"log_total_piezas" : 1.4545,"marca_vehiculo_encoded": 1,"valor_vehiculo": 3560, "valor_por_pieza": 150,"antiguedad_vehiculo": 1}

#X = pd.DataFrame(data=X)
linnear_regression.predict(df[["log_total_piezas","marca_vehiculo_encoded","valor_vehiculo","valor_por_pieza","antiguedad_vehiculo"]])

array([4.38408432, 2.94900912, 5.61743037, 6.16557582, 3.50630499,
       6.04471015, 5.75581344, 4.81765249, 4.98156999, 3.23150361])

In [13]:
X = pd.DataFrame(data=[X])
X

NameError: name 'X' is not defined

In [ ]:
X = pd.DataFrame(data=[{'claim_id': 561205, 'marca_vehiculo': 'ferd', 'antiguedad_vehiculo': 1, 'tipo_poliza': 1, 'taller': 4, 'partes_a_reparar': 3, 'partes_a_reemplazar': 2}])
X

In [ ]:
import pandas as pd

class InputData(BaseModel):
    claim_id: int | None = None
    marca_vehiculo: str
    antiguedad_vehiculo: int
    tipo_poliza: int
    taller: int
    partes_a_reparar: int
    partes_a_reemplazar: int

class MyDataClass:
    def __init__(self, col1, col2, col3):
        self.col1 = col1
        self.col2 = col2
        self.col3 = col3

# Create a list of instances
data_instances = [
    MyDataClass("spam", 1, True),
    MyDataClass("chips", 2, True),
    MyDataClass("eggs", 3, False)
]

# Convert the list of instances to a list of dictionaries using a list comprehension
list_of_dicts = [instance.__dict__ for instance in data_instances]

# Pass the list of dictionaries to the DataFrame constructor
df = pd.DataFrame(list_of_dicts)

print(df)