In [9]:
import pandas as pd
import numpy

df = pd.read_csv("claims_dataset.csv", delimiter="|")
df

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar
0,561205,ferd,1,1,4,3,2
1,528569,ferd,4,3,1,2,4
2,408550,NaN,2,4,1,4,2
3,208451,NaN,1,1,4,1,4
4,394115,ferd,2,4,1,3,4
5,243530,fait,2,1,3,1,2
6,288203,NaN,3,3,4,2,2
7,991981,ferd,3,3,2,1,2
8,435094,chepy,2,1,1,4,3
9,417848,fait,4,3,1,4,4

In [2]:
diccionario_imputacion = {
    'log_total_piezas': 1.4545,
    'marca_vehiculo_encoded': 0,
    'valor_vehiculo': 3560,
    'valor_por_pieza': 150,
    'antiguedad_vehiculo': 1,
    'tipo_poliza': 1,
    'taller': 1,
    'partes_a_reparar': 3,
    'partes_a_reemplazar': 1
}
#df.fillna(diccionario_imputacion)
df

,claim_id,marca_vehiculo,antiguedad_vehiculo,tipo_poliza,taller,partes_a_reparar,partes_a_reemplazar
0,561205,ferd,1,1,4,3,2
1,528569,ferd,4,3,1,2,4
2,408550,NaN,2,4,1,4,2
3,208451,NaN,1,1,4,1,4
4,394115,ferd,2,4,1,3,4
5,243530,fait,2,1,3,1,2
6,288203,NaN,3,3,4,2,2
7,991981,ferd,3,3,2,1,2
8,435094,chepy,2,1,1,4,3
9,417848,fait,4,3,1,4,4

In [11]:
import dill

with open('pipeline_1.pkl', 'rb') as file:
    # Load the object
    pipeline_1 = dill.load(file)
with open('pipeline_2.pkl', 'rb') as file:
    # Load the object
    pipeline_2 = dill.load(file)
with open('pipeline_3.pkl', 'rb') as file:
    # Load the object
    pipeline_3 = dill.load(file)
with open('pipeline_4.pkl', 'rb') as file:
    # Load the object
    pipeline_4 = dill.load(file)
with open('pipeline_5.pkl', 'rb') as file:
    # Load the object
    pipeline_5 = dill.load(file)
with open('linnear_regression.pkl', 'rb') as file:
    # Load the object
    linnear_regression = dill.load(file)

/home/enju/desafio-hdi/.venv/lib/python3.14/site-packages/sklearn/base.py:463: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.3.0 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [ ]:
pipeline_1(df)

:

In [10]:
# - 'log_total_piezas': float64
# - 'marca_vehiculo_encoded': int64
# - 'valor_vehiculo': int64
# - 'valor_por_pieza': int64
# - 'antiguedad_vehiculo': int64

X = {"log_total_piezas" : [1.4545],"marca_vehiculo_encoded": [1],"valor_vehiculo": [3560], "valor_por_pieza": [150],"antiguedad_vehiculo": [1]}
X = pd.DataFrame(data=X)
linnear_regression.predict(X)

array([6.20251814])